### ISSUE TITLE
Define the API spec for ClusterInventory

### ISSUE THREAD

**Issue by mikeshng** [kubernetes-sigs/cluster-inventory-api#2]
We have initial draft of the ClusterInventory API: https://docs.google.com/document/d/1sUWbe81BTclQ4Uax3flnCoKtEWngH-JA9MyCqljJCBM/

We will need a formal KEP to finalize the definition the API spec.

**Comment by justinsb** [comment]
Is a "strawman" CRD available anywhere?   I'd like to experiment with the API in practice, and it would be helpful to start from the right place :-)

**Comment by mikeshng** [comment]
Hi @justinsb there is still an ongoing discussion about the naming of the API.

https://kubernetes.slack.com/archives/C09R1PJR3/p1709219829408229
https://github.com/kubernetes/enhancements/pull/4323#issuecomment-1971370125
https://groups.google.com/g/kubernetes-sig-multicluster/c/A49euAgo7bM/m/fv3vXrqbAAAJ

We are also attending KubeCon EU to discuss more on this topic.

That being said. Should we push a CRD for now and mark it as experimental only so the community can start playing with it? WDYT?

**Comment by mikeshng** [comment]
KEP has been merged but there are more ongoing discussions around the naming of the API.

**Comment by mikeshng** [comment]
@justinsb PTAL https://github.com/kubernetes-sigs/cluster-inventory-api/pull/6 your feedback is most welcome.

**Comment by mikemorris** [comment]
Is there remaining work on this issue or can it be closed now that the KEP in kubernetes/enhancements#4323 and initial CRD design in #6 have merged?

**Comment by mikeshng** [comment]
You are right Mike. Let's close this one.

/close
